version: '3.9'
services:
    discord-bot:
        image: scw/discord-bot
        volumes:
            - './config.json:/home/node/app/config.json'
        container_name: discord-bot
        restart: unless-stopped
